### ISSUE TITLE
Invalid frontend map links for RDM

### ISSUE THREAD

**Issue by bschultz** [ccev/stopwatcher#23]
The links for stop and gym are invalid when using rdm frontend.

Instead of `{self.config.map_url}@pokestop/:{self.id}` and `{self.config.map_url}@gym/:{self.id}`
they should be `{self.config.map_url}@pokestop/{self.id}` and `{self.config.map_url}@gym/{self.id}`

**Comment by ccev** [comment]
fixed. thank you for reporting
(surprised it took so long for someone to notice. guess no one uses the rdm frontend 😳)
