### ISSUE TITLE
Easier use without Intel Watcher

### ISSUE THREAD

**Issue by ccev** [ccev/stopwatcher#38]
I don't even know what exactly to to if you don't want to scrape Portals.

**Comment by sunsetdk** [comment]
I have been trying to get it running with no portal scraper. But i can't get past the connection to the non existing portal database

**Comment by ccev** [comment]
@sunsetdk I think what you have to do is to set up an empty portal table (sql files can be found in the intelwatcher repo) and then link stopwatcher to it
